function tau = leg_convolution(F,Tp,phi1,phi2)
%LEG_CONVOLUTION
%    TAU = LEG_CONVOLUTION(F,Tp,PHI1,PHI2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    29-Oct-2025 20:00:18

t2 = conj(phi1);
t3 = conj(phi2);
t4 = cos(phi1);
t5 = sin(phi1);
t7 = phi1+phi2;
t6 = cos(t2);
t8 = sin(t2);
t9 = cos(t7);
t10 = sin(t7);
t11 = t2+t3;
t12 = t4./4.0;
t13 = t5./4.0;
t14 = cos(t11);
t15 = sin(t11);
t16 = t9.*(3.0./1.0e+1);
t17 = t10.*(3.0./1.0e+1);
t18 = t4.*t14.*5.0;
t19 = t5.*t15.*5.0;
t20 = t9.*t14;
t21 = t10.*t15;
t24 = t12+t16;
t25 = t5.*t6.*t9.*t15;
t28 = t4.*t8.*t10.*t14;
t29 = t13+t17;
t22 = t20.*6.0;
t23 = t21.*6.0;
t26 = t4.*t6.*t21;
t27 = t5.*t8.*t20;
t30 = abs(t29);
t31 = abs(t24);
t36 = t20+t21;
t32 = -t26;
t33 = -t27;
t34 = t31.^2;
t35 = t30.^2;
t39 = t18+t19+t22+t23;
t37 = t34+t35;
t43 = t25+t28+t32+t33;
t38 = 1.0./sqrt(t37);
t44 = 1.0./t43;
t40 = F.*t24.*t38;
t41 = F.*t29.*t38;
t45 = t24.*t36.*t44.*1.6e+1;
t46 = t29.*t36.*t44.*1.6e+1;
t47 = t9.*t39.*t44.*(4.0./5.0);
t48 = t10.*t39.*t44.*(4.0./5.0);
t49 = -t47;
t50 = -t48;
t51 = t45+t49;
t52 = t46+t50;
t53 = Tp.*t51;
t54 = Tp.*t52;
t55 = t40+t54;
tau = [(t6./4.0+t14.*(3.0./1.0e+1)).*(t41-t53)-t55.*(t8./4.0+t15.*(3.0./1.0e+1));t15.*t55.*(-3.0./1.0e+1)+t14.*(t41-t53).*(3.0./1.0e+1)];
end
